<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
	'Mail' => 'Почта',
	'Compose mail' => 'Написать письмо',
	'Sent mail' => 'Отправленные',
	'Mail data of users' => 'Почтовые данные пользователей',
	
	'Settings' => 'Настройки',
	'Users' => 'Пользователи',
	'Confirmation of user registration' => 'Подтверждение пользователей',
	'System' => 'Системные',
	'Clear cache' => 'Очистить кэш',
	'Clear all' => 'Очистить всё',
	'Create indexes for employees database' => 'Создать индексы базы данных сотрудников',
	'System settings' => 'Настройки системы',
	'Block site' => 'Блокировка сайта',
	
	'Log Out' => 'Выход',
	'Profile' => 'Профиль',
	'My profile' => 'Мой профиль',
	'Fix the menu at the top of the screen' => 'Закрепление меню вверху экрана',
);