<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
	'Message' => 'Сообщение',
	'Other' => 'Прочие',
	'Message successfully deleted!' => 'Сообщение успешно удалено!',
	
	'File ID' => 'ID файла',
	'Mail log ID' => 'ID в журнале сообщений',
	'File name' => 'Имя файла',
	'File' => 'Файл',
	
	'Subject' => 'Тема',
	'Text' => 'Текст',
	'Addresses' => 'Адресаты',
	'Carbon copy' => 'Копия',
	'Attach file' => 'Прикрепить файл:',
	'Sender (name)' => 'Отправитель (имя)',
	
	'No addresses selected.' => 'Не выбрано ни одного адресата.',
	'Unable to send a message.' => 'Не удалось отправить сообщение.',
	'Unable to add a file to the message log.' => 'Невозможно добавить файл в журнал сообщений.',
	'Error while saving the file in the message log. {error_text}.' => 'Ошибка при сохранении файла в журнал сообщений. {error_text}.',
	'Message not found.' => 'Сообщение не найдено.',
	'Failed to delete a file in the message log.' => 'Ошибка удаления файла в журнале сообщений.',
	
	'All' => 'Все',
	'Personal message' => 'Личное сообщение',
	'Personal message containing the report' => 'Личное сообщение, содержащее отчет',
	'Mailing' => 'Рассылка',
	'Reports for Accounting' => 'Отчеты для бухгалтерии',
	'Other' => 'Прочее',
	'Password recovery' => 'Восстановление пароля',
	'ID' => 'ID',
	'Date' => 'Дата',
	'Sender (user ID)' => 'Отправитель (id-пользователя)',
	'Recipients (E-mail)' => 'Получатели (E-mail)',
	'Recipients (user ID)' => 'Получатели (id-пользователей)',
	'Message type' => 'Тип сообщения',
	'File not found!' => 'Файл не найден!',
	
	'Sent messages log' => 'Журнал отправленных сообщений',
	'from' => 'с',
	'to' => 'по',
	'Search by date:' => 'Поиск по дате:',
	'Click to expand.' => 'Кликните, чтобы развернуть.',
	'Please, choose type' => 'Выберите тип',
	
	'Unable to get a list of email-addresses.' => 'Не удалось получить список email-адресов.',
	'The message successfully sent!' => 'Письмо успешно отправлено!',
	
	'Additional user data to send mail' => 'Данные пользователей для отправки почты',
	'To send mail through Exchange-server (Outlook), fill the following fields:' => 'Чтобы отправлять письма через Exchange-сервер (Outlook), заполните следующие поля:',
	'select the value' => 'выберите значение',
	'type the mail server, for example' => 'впишите адрес почтового сервера, например,',
	'type the mail username' => 'впишите email имя пользователя',
	'type the sender name, for example "Marty Seamus McFly"' => 'впишите имя отправителя, например, "Иванов Иван Иванович"',
	'Specify' => 'Укажите',
	'and' => 'и',
	'Messages sent through the Exchange are stored in the log of sent messages on the Outlook Web App client.' => 'Письма, отправленные через Exchange сохраняются в журнале отправленных писем на клиенте Outlook Web App.',
	'To connect to other mail server, for example to Gmail, fill the following fields:' => 'Чтобы подключиться к другой почте, например, к mail.ru, заполните следующие поля:',
	'type "tls"' => 'впишите "tls"',
	'type "smtp.gmail.com"' => 'впишите "smtp.mail.ru"',
	'type "587"' => 'впишите "587"',
	'type the E-mail of the sender.' => 'впишите email пользователя.',
	'://Host:' => '://Хост:',
);