<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return array(
	'Users' => 'Пользователи',
	'All' => 'Все',
	'all' => 'все',
    'New user' => 'Новый пользователь',
	'№' => '№',
	'Actions' => 'Действия',
	'Search' => 'Поиск',
	'Show' => 'Показать',
	'rows' => 'строк',
	
	'Title' => 'Название',
	'Comment' => 'Комментарий',
	'Removed' => 'Удалено',
	'The name already exists.' => 'Такое название уже существует.',
	'You can not to delete the records that are not marked as removed.' => 'Нельзя удалять записи, которые не помеченны на удаление.',
	'on all parameters' => 'по всем параметрам', // (Поиск) по всем параметрам
	'Minimum 3 characters' => 'От 3-х символов',
	'Create' => 'Добавить',
	'Mark the record as removed?' => 'Пометить на удаление?',
	'Close' => 'Закрыть',
	'Please check correctness of the surname, name and patronymic, as it can not be changed.' => 'Проверьте правильность заполнения фамилии, имени и отчества, т.к. их менять нельзя.',
	'Delete' => 'Удалить',
	'Restore' => 'Восстановить',
	
	'Reached maximum limit of attempts to recover passwords per day. Please, refer to the administrator of this site to recover your password or try to recover the password tomorrow.' => 'Достигнут лимит максимальных попыток восстановления паролей за день. Обратитесь к администратору сайта за восстановлением или попробуйте восстановить пароль завтра.',
	'You can not restore the system user.' => 'Нельзя восстанавливать системного пользователя.',
	'A user with the "E-mail" or "username" does not exist or is blocked.' => 'Пользователь с указанным "E-mail" или "Имя пользователя" не существует или заблокирован.',
	'Username or E-mail' => 'Имя пользователя или электронная почта',
	'Recovery code' => 'Код восстановления',
	'Text in the image' => 'Символы с картинки',
	
	'Super administrator' => 'Супер администратор',
	'Administrator' => 'Администратор',
	
	'Table with users not found in database. May be the application not installed. Contact your site administrator.' => 'Таблица с пользователями не найдена в базе данных. Возможно, приложение не установлено. Обратитесь к администратору сайта.',
	'Access is denied!' => 'Доступ запрещен!',
	
	'Default' => 'По умолчанию',
	'Exchange' => 'Exchange',
	'The reference to recovery is incorrect or expired.' => 'Ссылка на восстановление неверна или просрочена.',
	
	'E-mail / mailing' => 'E-mail / Рассылка',
	'Phone / IP-address' => 'Телефон/ IP-адрес',
	
	'User:' => 'Пользователь',
	'Registrated:' => 'Зарегистрирован',
	'Registrated!' => 'Зарегистрирован!',
	'Not confirmed!' => 'Не подтвержден!',
	'Blocked!' => 'Заблокирован!',
	
	'Registration' => 'Регистрация',
	'Registration form' => 'Форма регистрации',
	'Login' => 'Вход',
	'Your IP-address' => 'Ваш IP-адрес',
	'Sign in' => 'Войти',
	'Forgot password?' => 'Забыли пароль?',
	'E-mail or username...' => 'E-mail или Имя пользователя...',
	'Recover' => 'Восстановить',
	'Type the characters from the image. Characters are not case sensitive.' => 'Введите символы с картинки. Символы не чувствительны к регистру.',
	'Another code' => 'Другой код',
	
	'User profile' => 'Профиль пользователя',
	'Password recovery' => 'Восстановление пароля',
	'Link to reset sent to your email.' => 'Ссылка для восстановления отправлена на вашу электронную почту.',
	'Dear {full_name}.' => 'Уважаемый {full_name}',
	'You sent a letter to the password recovery. If you did not, you should contact the site administrator, because maybe someone is trying to hack into your account.' => 'Вами было отправлено письмо на восстановление пароля. Если это сделали не вы, то стоит обратиться к администратору сайта, т.к., возможно, кто-то пытается взломать вашу учетную запись.',
	'To reset your password, click on this link:' => 'Для восстановления учетной записи перейдите по этой ссылке:',
	'Link to reset your password.' => 'Ссылка восстановления учетной записи.',
	'If the link is not displayed correctly, go to this address:' => 'Если ссылка отображается некорректно, то перейдите по этому адресу:',
	'Application has been accepted' => 'Заявка принята',
	'Your application has been accepted, please expect your account confirmation by the site administrator. Then you can log in with your username and password.' => 'Ваша заявка принята, ожидайте подтверждения администратора сайта. После этого вы можете войти в систему под своим именем пользователя и паролем.',
	'Go to the login page' => 'Перейти на страницу входа',
	'Confirmation of user registration' => 'Подтверждение регистрации пользователей',
	'Application for registration' => 'Заявка на регистрацию',
	'Another code' => 'Другой код',
	'Sign up' => 'Регистрация',
	'Confirm' => 'Подтвердить',
);